version: '3.8'

services:
  db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    depends_on :
      db:
        condition: service_healthy
    command: python3 manage.py runserver 0.0.0.0:80
    ports:
      - "8001:80"
    volumes:
      - .:/usr/src/app/
    restart: always
    env_file:
      - ./.env
