# Generated by Django 5.0.1 on 2024-01-05 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('input_text', models.TextField()),
                ('summary_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.CreateModel(
            name='SummaryChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified at')),
                ('chunk_text', models.TextField()),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.summary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
